spring:
  application:
    name: commissions-service
  cloud:
    stream:
      function:
        definition: registrationEventConsumer
      bindings:
        registrationEventConsumer-in-0:
          destination: registration-event
  zipkin:
    base-url: http://localhost:9411
authentication-dev:
  auth:
    tokenSecret: myTokenSecret
    tokenExpirationMsec: 3600000 #1 hour
    refreshTokenExpirationMsec: 77760000000 #90 days
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken

